//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFirstApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class usertable
    {
        public int userid { get; set; }
        public string username { get; set; }
        public string pwd { get; set; }
        public string country { get; set; }
        [Required]
        public string gender { get; set; }
    }
}
